[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
version = "0.0.14"
edition = "2021"
rust-version = "1.65"
authors = ["Wormhole Contributors"]
license = "Apache-2.0"
homepage = "https://github.com/wormhole-foundation/wormhole-sdk-rs"
repository = "https://github.com/wormhole-foundation/wormhole-sdk-rs"

[workspace.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[workspace.dependencies]
alloy-primitives = "0.2.0"
hex-literal = "0.4.1"
anchor-lang = "0.28.0"

serde = "1.0.171"
serde_json = "1.0.103"

wormhole-vaas = { path = "crates/vaas" }
wormhole-explorer-client = { path = "crates/explorer-client" }