[package]
name = "wormhole-io"
description = "Traits for Wormhole payload serialization/deserialization"

version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
alloy-primitives = { workspace = true, optional = true }

[features]
alloy = ["dep:alloy-primitives"]